### PR TITLE
[fix] Add quotes around the workspace name

### LINKED ISSUE #36: Fails to handle Workspace with spaces in name
Due to the parameter "self.workspace" being put straight into the command line, if the workspace has any spaces in the name, any command using the workspace name will fail.

### PR DESCRIPTION
**Pull request by cwill747**
Fixes #36 

Adds single quotes around the workspace name to account for possible spaces.

### CODE REVIEW

**Comment by WtfJoke** [comment]
First of all, thanks again for the fix and not just for the reporting of the issue :smile: 

To the change itself. I thought it might be better if we quote the workspace already in the configobject. 
Or what do you think about that?

Most likely we hit the same issue, when we have a streamname with space.

And if you agree, would you implement it directly on this pr or should I do it afterwards? :point_up:

**Comment by cwill747** [comment]
Duh... That makes way more sense. I will make the change in my PR :)

**Comment by WtfJoke** [comment]
Perfect!

**Comment by cwill747** [comment]
How do you feel about changing it to use Python3's string formatting? Would let us do something like 

```python
command = "scm --show-alias n --show-uuid y list baselines --components {component} -r {config.repo} -u {config.user} -P {config.password} -m 20000".format(component=entry.component, config=config)
```

**Comment by cwill747** [comment]
OK Done, changed in configuration.py instead of rtcFunctions. Tested locally, seems to work ok.

**Comment by cwill747** [comment]
Just kidding, saw what you meant. I used shlex.quote(), I think it might cover some more use cases than your shell file. If you'd rather me use shell.quote, that's fine by me.

**Comment by WtfJoke** [comment]
> Just kidding, saw what you meant. I used shlex.quote(), I think it might cover some more use cases than your shell file. If you'd rather me use shell.quote, that's fine by me.

Nah, I preferr to have shlex.quote too as long as it works. :smile:  For me shlex.quote didnt worked out for the usecase I had (but I forgot the details about it, why it didnt worked)


> How do you feel about changing it to use Python3's string formatting?

That looks cool :yum:  Tell me if you like to do that or else you can open an issue for that and I will work on that as soon as I can. :)

**Comment by cwill747** [comment]
Would be happy changing to python3's string formatting, would give me something to do :smile:

**Comment by WtfJoke** [comment]
Haha sure, go for it! I appreciate if you can do that :+1:

**Pull request merged**
