### PR TITLE
Fixed comparison

### PR DESCRIPTION
**Pull request by jacobilsoe**
Fixed a number comparison (#55).

### CODE REVIEW

**Comment by WtfJoke** [comment]
A question here.  Why the previous code didnt worked out? I see the failing test. Is it like an object comparsion thing?

**Comment by jacobilsoe** [comment]
Yes, it is a comparison issue. Try this in a python interpreter: 500 is len(range(500))
Then try: 100 is len(range(100))

**Comment by WtfJoke** [comment]
Ah I see. How come it works until 100 :question: That seems strange.

**Comment by ohumbel** [comment]
Maybe an implementation detail:

```
luna:rtc2git oti$ python3
Python 3.4.3 (v3.4.3:9b73f1c3e601, Feb 23 2015, 02:52:03) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> 500 is len(range(500))
False
>>> 100 is len(range(100))
True
>>> 200 is len(range(200))
True
>>> 300 is len(range(300))
False
>>> 250 is len(range(250))
True
>>> 255 is len(range(255))
True
>>> 256 is len(range(256))
True
>>> 257 is len(range(257))
False
>>>
```

**Comment by WtfJoke** [comment]
Looks like. Thank you guys

**Pull request merged**
