### PR TITLE
Added configuration of change set accept max count

### LINKED ISSUE #55: Configuration of conflict resolver
It would be nice to have an option to control what change sets the conflict resolver picks to accept. 

Right now, only change sets belonging to the same author or change sets with "merge" in the comment text are accepted together. I have several examples where change sets from different authors need to be accepted together to resolve a conflict.

IMO, the resolver should continue accepting change sets together until there are no more change sets. - and only then give up. It should succeed at some point.

### PR DESCRIPTION
**Pull request by jacobilsoe**
Fixes #55.

### CODE REVIEW

**Comment by jacobilsoe** [comment]
Found a small issue.

**Comment by ohumbel** [comment]
No problem, take your time.
Meanwhile I might be able to improve the 7 tests failing on the command line. This will conflict with your changes to test_configuration.py. But it should be really easy to merge (4 lines with trivial changes).

**Comment by jacobilsoe** [comment]
I think my problems were caused by a bad history file. Please review the pull request. I will investigate some more meanwhile.

**Comment by ohumbel** [comment]
looks good - thanks!

**Pull request merged**
